#include "utils.h"
#include "hwinit.h"
#include "lib/printk.h"
#include "display/video_fb.h"

#include "fuse.h"
#include "hwinit/btn.h"

#define XVERSION 1

static void reset_using_pmc()
{
    volatile uint32_t *reset;

    reset = (uint32_t *)0x7000e400;
    *reset |= (1 << 4);
}

int main(void) {
    u32 *lfb_base;

    nx_hwinit();
    display_init();

    // Set up the display, and register it as a printk provider.
    lfb_base = display_init_framebuffer();
    video_init(lfb_base);

    printk("                                         fusedump\n");
    printk("                                            v%d\n", XVERSION);

    printk("FUSE_PRODUCTION_MODE: %08x\n", FUSE_CHIP_REGS->FUSE_PRODUCTION_MODE);
    printk("FUSE_SKU_INFO: %08x\n", FUSE_CHIP_REGS->FUSE_SKU_INFO);
    printk("FUSE_CPU_SPEEDO_0: %08x\n", FUSE_CHIP_REGS->FUSE_CPU_SPEEDO_0);
    printk("FUSE_CPU_IDDQ: %08x\n", FUSE_CHIP_REGS->FUSE_CPU_IDDQ);
    printk("FUSE_FT_REV: %08x\n", FUSE_CHIP_REGS->FUSE_FT_REV);
    printk("FUSE_CPU_SPEEDO_1: %08x\n", FUSE_CHIP_REGS->FUSE_CPU_SPEEDO_1);
    printk("FUSE_CPU_SPEEDO_2: %08x\n", FUSE_CHIP_REGS->FUSE_CPU_SPEEDO_2);
    printk("FUSE_SOC_SPEEDO_0: %08x\n", FUSE_CHIP_REGS->FUSE_SOC_SPEEDO_0);
    printk("FUSE_SOC_SPEEDO_1: %08x\n", FUSE_CHIP_REGS->FUSE_SOC_SPEEDO_1);
    printk("FUSE_SOC_SPEEDO_2: %08x\n", FUSE_CHIP_REGS->FUSE_SOC_SPEEDO_2);
    printk("FUSE_SOC_IDDQ: %08x\n", FUSE_CHIP_REGS->FUSE_SOC_IDDQ);
    printk("FUSE_FA: %08x\n", FUSE_CHIP_REGS->FUSE_FA);
    printk("FUSE_PUBLIC_KEY: %08x%08x%08x%08x%08x%08x%08x%08x\n", FUSE_CHIP_REGS->FUSE_PUBLIC_KEY[0], FUSE_CHIP_REGS->FUSE_PUBLIC_KEY[1], FUSE_CHIP_REGS->FUSE_PUBLIC_KEY[2], FUSE_CHIP_REGS->FUSE_PUBLIC_KEY[3], FUSE_CHIP_REGS->FUSE_PUBLIC_KEY[4], FUSE_CHIP_REGS->FUSE_PUBLIC_KEY[5], FUSE_CHIP_REGS->FUSE_PUBLIC_KEY[6]);
    printk("FUSE_TSENSOR_1: %08x\n", FUSE_CHIP_REGS->FUSE_TSENSOR_1);
    printk("FUSE_TSENSOR_2: %08x\n", FUSE_CHIP_REGS->FUSE_TSENSOR_2);
    printk("FUSE_CP_REV: %08x\n", FUSE_CHIP_REGS->FUSE_CP_REV);
    printk("FUSE_TSENSOR_0: %08x\n", FUSE_CHIP_REGS->FUSE_TSENSOR_0);
    printk("FUSE_FIRST_BOOTROM_PATCH_SIZE_REG: %08x\n", FUSE_CHIP_REGS->FUSE_FIRST_BOOTROM_PATCH_SIZE_REG);
    printk("FUSE_SECURITY_MODE: %08x\n", FUSE_CHIP_REGS->FUSE_SECURITY_MODE);
    printk("FUSE_PRIVATE_KEY: %08x%08x%08x%08x\n", FUSE_CHIP_REGS->FUSE_PRIVATE_KEY[0], FUSE_CHIP_REGS->FUSE_PRIVATE_KEY[1], FUSE_CHIP_REGS->FUSE_PRIVATE_KEY[2]);
    printk("FUSE_DEVICE_KEY: %08x\n", FUSE_CHIP_REGS->FUSE_DEVICE_KEY);
    printk("FUSE_RESERVED_SW: %08x\n", FUSE_CHIP_REGS->FUSE_RESERVED_SW);
    printk("FUSE_VP8_ENABLE: %08x\n", FUSE_CHIP_REGS->FUSE_VP8_ENABLE);
    printk("FUSE_RESERVED_ODM: %08x%08x%08x%08x%08x%08x%08x%08x\n", FUSE_CHIP_REGS->FUSE_RESERVED_ODM[0], FUSE_CHIP_REGS->FUSE_RESERVED_ODM[1], FUSE_CHIP_REGS->FUSE_RESERVED_ODM[2], FUSE_CHIP_REGS->FUSE_RESERVED_ODM[3], FUSE_CHIP_REGS->FUSE_RESERVED_ODM[4], FUSE_CHIP_REGS->FUSE_RESERVED_ODM[5], FUSE_CHIP_REGS->FUSE_RESERVED_ODM[6]);
    printk("FUSE_SKU_USB_CALIB: %08x\n", FUSE_CHIP_REGS->FUSE_SKU_USB_CALIB);
    printk("FUSE_SKU_DIRECT_CONFIG: %08x\n", FUSE_CHIP_REGS->FUSE_SKU_DIRECT_CONFIG);
    printk("FUSE_VENDOR_CODE: %08x\n", FUSE_CHIP_REGS->FUSE_VENDOR_CODE);
    printk("FUSE_FAB_CODE: %08x\n", FUSE_CHIP_REGS->FUSE_FAB_CODE);
    printk("FUSE_LOT_CODE_0: %08x\n", FUSE_CHIP_REGS->FUSE_LOT_CODE_0);
    printk("FUSE_LOT_CODE_1: %08x\n", FUSE_CHIP_REGS->FUSE_LOT_CODE_1);
    printk("FUSE_WAFER_ID: %08x\n", FUSE_CHIP_REGS->FUSE_WAFER_ID);
    printk("FUSE_X_COORDINATE: %08x\n", FUSE_CHIP_REGS->FUSE_X_COORDINATE);
    printk("FUSE_Y_COORDINATE: %08x\n", FUSE_CHIP_REGS->FUSE_Y_COORDINATE);
    printk("FUSE_SATA_CALIB: %08x\n", FUSE_CHIP_REGS->FUSE_SATA_CALIB);
    printk("FUSE_GPU_IDDQ: %08x\n", FUSE_CHIP_REGS->FUSE_GPU_IDDQ);
    printk("FUSE_TSENSOR_3: %08x\n", FUSE_CHIP_REGS->FUSE_TSENSOR_3);
    printk("FUSE_OPT_SUBREVISION: %08x\n", FUSE_CHIP_REGS->FUSE_OPT_SUBREVISION);
    printk("FUSE_TSENSOR_4: %08x\n", FUSE_CHIP_REGS->FUSE_TSENSOR_4);
    printk("FUSE_TSENSOR_5: %08x\n", FUSE_CHIP_REGS->FUSE_TSENSOR_5);
    printk("FUSE_TSENSOR_6: %08x\n", FUSE_CHIP_REGS->FUSE_TSENSOR_6);
    printk("FUSE_TSENSOR_7: %08x\n", FUSE_CHIP_REGS->FUSE_TSENSOR_7);
    printk("FUSE_OPT_PRIV_SEC_DIS: %08x\n", FUSE_CHIP_REGS->FUSE_OPT_PRIV_SEC_DIS);
    printk("FUSE_PKC_DISABLE: %08x\n", FUSE_CHIP_REGS->FUSE_PKC_DISABLE);
    printk("FUSE_TSENSOR_COMMON: %08x\n", FUSE_CHIP_REGS->FUSE_TSENSOR_COMMON);
    printk("FUSE_DEBUG_AUTH_OVERRIDE: %08x\n", FUSE_CHIP_REGS->FUSE_DEBUG_AUTH_OVERRIDE);
    printk("FUSE_TSENSOR_8: %08x\n", FUSE_CHIP_REGS->FUSE_TSENSOR_8);
    printk("FUSE_RESERVED_CALIB: %08x\n", FUSE_CHIP_REGS->FUSE_RESERVED_CALIB);
    printk("FUSE_TSENSOR_9: %08x\n", FUSE_CHIP_REGS->FUSE_TSENSOR_9);
    printk("FUSE_USB_CALIB_EXT: %08x\n", FUSE_CHIP_REGS->FUSE_USB_CALIB_EXT);
    printk("FUSE_SPARE_BIT: %08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x%08x\n", FUSE_CHIP_REGS->FUSE_SPARE_BIT[0], FUSE_CHIP_REGS->FUSE_SPARE_BIT[1], FUSE_CHIP_REGS->FUSE_SPARE_BIT[2], FUSE_CHIP_REGS->FUSE_SPARE_BIT[3], FUSE_CHIP_REGS->FUSE_SPARE_BIT[4], FUSE_CHIP_REGS->FUSE_SPARE_BIT[5], FUSE_CHIP_REGS->FUSE_SPARE_BIT[6], FUSE_CHIP_REGS->FUSE_SPARE_BIT[7], FUSE_CHIP_REGS->FUSE_SPARE_BIT[8], FUSE_CHIP_REGS->FUSE_SPARE_BIT[9], FUSE_CHIP_REGS->FUSE_SPARE_BIT[10], FUSE_CHIP_REGS->FUSE_SPARE_BIT[11], FUSE_CHIP_REGS->FUSE_SPARE_BIT[12], FUSE_CHIP_REGS->FUSE_SPARE_BIT[13], FUSE_CHIP_REGS->FUSE_SPARE_BIT[14],FUSE_CHIP_REGS->FUSE_SPARE_BIT[15], FUSE_CHIP_REGS->FUSE_SPARE_BIT[16], FUSE_CHIP_REGS->FUSE_SPARE_BIT[17], FUSE_CHIP_REGS->FUSE_SPARE_BIT[18], FUSE_CHIP_REGS->FUSE_SPARE_BIT[19], FUSE_CHIP_REGS->FUSE_SPARE_BIT[20], FUSE_CHIP_REGS->FUSE_SPARE_BIT[21], FUSE_CHIP_REGS->FUSE_SPARE_BIT[22], FUSE_CHIP_REGS->FUSE_SPARE_BIT[23], FUSE_CHIP_REGS->FUSE_SPARE_BIT[24], FUSE_CHIP_REGS->FUSE_SPARE_BIT[25], FUSE_CHIP_REGS->FUSE_SPARE_BIT[26], FUSE_CHIP_REGS->FUSE_SPARE_BIT[27], FUSE_CHIP_REGS->FUSE_SPARE_BIT[28], FUSE_CHIP_REGS->FUSE_SPARE_BIT[29], FUSE_CHIP_REGS->FUSE_SPARE_BIT[30]);

    // credits
    printk("\n                       fusee gelee by @ktemkin, fusedump by @skiilaa\n");

    // Wait for the power button, and then reset.
    while (btn_read() != BTN_POWER);

    // Reset.
    reset_using_pmc();

    /* Do nothing for now */
    return 0;
}
